CREATE TABLE IF NOT EXISTS calendar_events (
    id BIGSERIAL PRIMARY KEY,
    relationship_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    event_type VARCHAR(30) NOT NULL DEFAULT 'CUSTOM',
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    all_day BOOLEAN NOT NULL DEFAULT false,
    repeat_type VARCHAR(30) NOT NULL DEFAULT 'NONE',
    reminder_minutes INT,
    color VARCHAR(30),
    created_by BIGINT NOT NULL,
    updated_by BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS holiday_calendar (
    id BIGSERIAL PRIMARY KEY,
    date DATE NOT NULL,
    name_zh VARCHAR(100) NOT NULL,
    name_en VARCHAR(100),
    type VARCHAR(30) NOT NULL,
    lunar_date VARCHAR(50),
    is_holiday BOOLEAN NOT NULL DEFAULT false,
    is_workday BOOLEAN NOT NULL DEFAULT false,
    description_zh TEXT,
    description_en TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_calendar_events_relationship_id ON calendar_events (relationship_id);
CREATE INDEX IF NOT EXISTS idx_calendar_events_start_time ON calendar_events (start_time);
CREATE INDEX IF NOT EXISTS idx_calendar_events_status ON calendar_events (status);
CREATE INDEX IF NOT EXISTS idx_holiday_calendar_date ON holiday_calendar (date);
CREATE INDEX IF NOT EXISTS idx_holiday_calendar_type ON holiday_calendar (type);
CREATE UNIQUE INDEX IF NOT EXISTS ux_holiday_calendar_date_name_type ON holiday_calendar (date, name_zh, type);

INSERT INTO holiday_calendar (date, name_zh, name_en, type, lunar_date, is_holiday, is_workday, description_zh, description_en)
VALUES
('2026-01-01', '元旦', 'New Year''s Day', 'FESTIVAL', NULL, true, false, '公历新年。', 'Gregorian New Year.'),
('2026-02-14', '情人节', 'Valentine''s Day', 'FESTIVAL', NULL, false, false, NULL, NULL),
('2026-03-08', '妇女节', 'International Women''s Day', 'FESTIVAL', NULL, false, false, NULL, NULL),
('2026-05-01', '劳动节', 'Labor Day', 'FESTIVAL', NULL, true, false, NULL, NULL),
('2026-06-01', '儿童节', 'Children''s Day', 'FESTIVAL', NULL, false, false, NULL, NULL),
('2026-10-01', '国庆节', 'National Day', 'FESTIVAL', NULL, true, false, NULL, NULL),
('2026-12-25', '圣诞节', 'Christmas Day', 'FESTIVAL', NULL, false, false, NULL, NULL),
('2026-02-17', '春节', 'Spring Festival', 'FESTIVAL', '正月初一', true, false, '农历新年。', 'Chinese Lunar New Year.'),
('2026-03-03', '元宵节', 'Lantern Festival', 'FESTIVAL', '正月十五', false, false, NULL, NULL),
('2026-04-05', '清明节', 'Qingming Festival', 'FESTIVAL', NULL, true, false, NULL, NULL),
('2026-06-19', '端午节', 'Dragon Boat Festival', 'FESTIVAL', '五月初五', true, false, NULL, NULL),
('2026-09-25', '中秋节', 'Mid-Autumn Festival', 'FESTIVAL', '八月十五', true, false, NULL, NULL),
('2027-01-01', '元旦', 'New Year''s Day', 'FESTIVAL', NULL, true, false, '公历新年。', 'Gregorian New Year.'),
('2027-02-14', '情人节', 'Valentine''s Day', 'FESTIVAL', NULL, false, false, NULL, NULL),
('2027-03-08', '妇女节', 'International Women''s Day', 'FESTIVAL', NULL, false, false, NULL, NULL),
('2027-05-01', '劳动节', 'Labor Day', 'FESTIVAL', NULL, true, false, NULL, NULL),
('2027-06-01', '儿童节', 'Children''s Day', 'FESTIVAL', NULL, false, false, NULL, NULL),
('2027-10-01', '国庆节', 'National Day', 'FESTIVAL', NULL, true, false, NULL, NULL),
('2027-12-25', '圣诞节', 'Christmas Day', 'FESTIVAL', NULL, false, false, NULL, NULL),
('2027-02-06', '春节', 'Spring Festival', 'FESTIVAL', '正月初一', true, false, '农历新年。', 'Chinese Lunar New Year.'),
('2027-02-20', '元宵节', 'Lantern Festival', 'FESTIVAL', '正月十五', false, false, NULL, NULL),
('2027-04-05', '清明节', 'Qingming Festival', 'FESTIVAL', NULL, true, false, NULL, NULL),
('2027-06-09', '端午节', 'Dragon Boat Festival', 'FESTIVAL', '五月初五', true, false, NULL, NULL),
('2027-09-15', '中秋节', 'Mid-Autumn Festival', 'FESTIVAL', '八月十五', true, false, NULL, NULL),
('2026-01-05', '小寒', 'Minor Cold', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-01-20', '大寒', 'Major Cold', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-02-04', '立春', 'Start of Spring', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-02-18', '雨水', 'Rain Water', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-03-05', '惊蛰', 'Awakening of Insects', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-03-20', '春分', 'Spring Equinox', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-04-05', '清明', 'Pure Brightness', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-04-20', '谷雨', 'Grain Rain', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-05-05', '立夏', 'Start of Summer', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-05-21', '小满', 'Grain Buds', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-06-05', '芒种', 'Grain in Ear', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-06-21', '夏至', 'Summer Solstice', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-07-07', '小暑', 'Minor Heat', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-07-23', '大暑', 'Major Heat', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-08-07', '立秋', 'Start of Autumn', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-08-23', '处暑', 'End of Heat', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-09-07', '白露', 'White Dew', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-09-23', '秋分', 'Autumn Equinox', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-10-08', '寒露', 'Cold Dew', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-10-23', '霜降', 'Frost Descent', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-11-07', '立冬', 'Start of Winter', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-11-22', '小雪', 'Minor Snow', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-12-07', '大雪', 'Major Snow', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2026-12-22', '冬至', 'Winter Solstice', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-01-05', '小寒', 'Minor Cold', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-01-20', '大寒', 'Major Cold', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-02-04', '立春', 'Start of Spring', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-02-19', '雨水', 'Rain Water', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-03-06', '惊蛰', 'Awakening of Insects', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-03-21', '春分', 'Spring Equinox', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-04-05', '清明', 'Pure Brightness', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-04-20', '谷雨', 'Grain Rain', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-05-06', '立夏', 'Start of Summer', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-05-21', '小满', 'Grain Buds', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-06-06', '芒种', 'Grain in Ear', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-06-21', '夏至', 'Summer Solstice', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-07-07', '小暑', 'Minor Heat', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-07-23', '大暑', 'Major Heat', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-08-08', '立秋', 'Start of Autumn', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-08-23', '处暑', 'End of Heat', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-09-08', '白露', 'White Dew', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-09-23', '秋分', 'Autumn Equinox', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-10-08', '寒露', 'Cold Dew', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-10-23', '霜降', 'Frost Descent', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-11-07', '立冬', 'Start of Winter', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-11-22', '小雪', 'Minor Snow', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-12-07', '大雪', 'Major Snow', 'SOLAR_TERM', NULL, false, false, NULL, NULL),
('2027-12-22', '冬至', 'Winter Solstice', 'SOLAR_TERM', NULL, false, false, NULL, NULL)
ON CONFLICT (date, name_zh, type) DO NOTHING;
